### ISSUE TITLE
Wind Direction calibration

### ISSUE THREAD

**Issue by NWItaly** [sparkfun/SparkFun_Weather_Meter_Kit_Arduino_Library#3]
Is it possibile choose which calibration to use? I would like to use SparkFun Weather Shield calibration.

**Comment by sfe-SparkFro** [comment]
Hi there! We had implemented a feature that should automatically select the calibration values for whatever platform is selected, but looks like we forgot to properly finish that. Oops! I just merged those changes and cut a new v1.1.0 release. Please try it out, it should select the calibration needed for the Weather Shield. If not, also please check out Examples 2 and 3, they demonstrate how to manually set the calibration values if needed.

Hope this helps! I'm going to close this issue as I believe this should be resolved with the v1.1.0 release and the examples, but please feel free to open it again if not. Thanks!
